services:
  postgres-webapp:
    image: "postgres:18.1-alpine"
    environment:
      POSTGRES_USER: "${DB_USER:-}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-}"
      POSTGRES_DB: "${DB_NAME:-}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-} -d ${DB_NAME:-}"]
      interval: 3s
      timeout: 5s
      retries: 30
    volumes:
      - "postgres-webapp_data:/var/lib/postgresql"
    restart: "unless-stopped"
  postgres-temporal:
    image: "postgres:18.1-alpine"
    environment:
      POSTGRES_USER: "temporal"
      POSTGRES_PASSWORD: "temporal"
      POSTGRES_DB: "temporal"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 3s
      timeout: 5s
      retries: 30
    volumes:
      - "postgres-temporal_data:/var/lib/postgresql"
    restart: "unless-stopped"
  temporal:
    image: "temporalio/auto-setup:1.29"
    environment:
      DB: "postgres12"
      DB_PORT: "5432"
      POSTGRES_USER: "temporal"
      POSTGRES_PWD: "temporal"
      POSTGRES_SEEDS: "postgres-temporal"
      TEMPORAL_ADDRESS: "temporal:7233"
      TEMPORAL_CLI_ADDRESS: "temporal:7233"
    healthcheck:
      test: ["CMD-SHELL", "temporal operator cluster health"]
      interval: 3s
      timeout: 5s
      retries: 30
    restart: "unless-stopped"
    depends_on:
      postgres-temporal:
        condition: "service_healthy"
  temporal-ui:
    image: "temporalio/ui:2.48.2"
    environment:
      TEMPORAL_ADDRESS: "temporal:7233"
      TEMPORAL_CORS_ORIGINS: "http://localhost:8233"
      TEMPORAL_UI_PORT: "8233"
      TEMPORAL_HIDE_LOGS: "true" # Don't re-print logs from Temporal service
    ports:
      - "${TEMPORAL_UI_PORT:-18001}:8233"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost:8233 || exit 1"]
    restart: "unless-stopped"
    depends_on:
      temporal:
        condition: "service_healthy"
  volume-permission-helper:
    image: "alpine"
    volumes:
      - "webapp-worker_storage:/storage"
    command: >
      sh -c "
        chown -R 1001:1001 /storage &&
        echo 'Volume permissions fixed' &&
        exit 0
      "
    restart: "on-failure"

volumes:
  postgres-temporal_data:
  postgres-webapp_data:
  webapp-worker_storage:
