services:
  webapp:
    build:
      context: "web"
      target: "development"
    volumes:
      - "./web:/app"
      - "webapp_deps:/app/node_modules/"
      - "webapp_next:/app/.next/"
      - "./:/workspace" # Workspace for devcontainer
      - "webapp_deps:/workspace/web/node_modules/"
      - "webapp_next:/workspace/web/.next/"
  inbucket:
    image: "inbucket/inbucket:sha-6eff554"
    environment:
      INBUCKET_MAILBOXNAMING: "full"
      INBUCKET_SMTP_ADDR: "0.0.0.0:25"
      INBUCKET_POP3_ADDR: "0.0.0.0:110"
    ports:
      - "18004:9000"
    healthcheck:
      test:
        ["CMD-SHELL", "wget --spider http://localhost:9000/status || exit 1"]
volumes:
  webapp_deps:
  webapp_next:
