services:
  webapp:
    build:
      context: "web"
      target: "development"
    volumes:
      - "./web:/app"
      - "webapp_deps:/app/node_modules/"
      - "webapp_next:/app/.next/"
      - "./:/workspace" # Workspace for devcontainer
      - "webapp_deps:/workspace/web/node_modules/"
      - "webapp_next:/workspace/web/.next/"

volumes:
  webapp_deps:
  webapp_next:
