version: "3"
dotenv:
  - .env
silent: true
vars:
  DOCKER_COMPOSE_SCRIPT:
    sh: |
      if [ "{{.APP_ENV}}" = "development" ]; then
        echo "docker compose -f compose.yml -f compose.dev.yml"
      else
        echo "docker compose -f compose.yml"
      fi
tasks:
  up:
    cmds:
      - '{{.DOCKER_COMPOSE_SCRIPT}} {{ if eq .FILESYSTEM_DISK "rustfs" }}--profile rustfs{{ end }} {{if eq .USE_EXTERNAL_SELENIUM "false"}}--profile selenium{{ end }} up --detach --build --remove-orphans'
      - "{{.DOCKER_COMPOSE_SCRIPT}} exec webapp task migrate"
  down:
    cmds:
      - "{{.DOCKER_COMPOSE_SCRIPT}} down"
  status:
    cmds:
      - "{{.DOCKER_COMPOSE_SCRIPT}} ps --format 'table {{\"{{.Name}}\"}}\t{{\"{{.Image}}\"}}\t{{\"{{.Status}}\"}}' --all"
  logs:
    cmds:
      - "{{.DOCKER_COMPOSE_SCRIPT}} logs --follow --tail=100"
  lint:
    cmds:
      - "{{.DOCKER_COMPOSE_SCRIPT}} exec webapp npm run lint"
  db:
    cmds:
      - "{{.DOCKER_COMPOSE_SCRIPT}} exec postgres-webapp psql -U {{.DB_USER}} -d {{.DB_NAME}}"
  stop:
    cmds:
      - '{{.DOCKER_COMPOSE_SCRIPT}} {{ if eq .FILESYSTEM_DISK "rustfs" }}--profile rustfs{{ end }} {{if eq .USE_EXTERNAL_SELENIUM "false"}}--profile selenium{{ end }} stop'
  migrate:
    cmds:
      - "{{.DOCKER_COMPOSE_SCRIPT}} run --build --rm webapp-migration-runner task migrate"
