export const QUERY_KEY_PROJECTS = 'projects'
export const QUERY_KEY_BUILDS = 'builds'
export const QUERY_KEY_SNAPSHOTS = 'snapshots'
export const QUERY_KEY_PAGE_RULES = 'page_rules'
export const QUERY_KEY_BUILD_LOGS = 'build_logs'
