name: Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - develop
      - main

jobs:
  # Perform release with semantic-release
  release:
    name: Release
    # TODO: Limit to main when main is used as stable branch
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      # id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    defaults:
      run:
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "web/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: /opt/spotteur-scripts/deploy.sh ${{ github.ref }} ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
