branches:
  - main
  - name: develop
    channel: beta
    prerelease: true
  - name: "feature/*"
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
tagFormat: "v${version}"
