branches:
  - main
  - name: develop
    channel: beta
    prerelease: beta
  - name: 'feature/*'
    prerelease: "${name.replace(/^feature\\//, 'feature-')}"
    channel: 'feature'

plugins:
  - '@semantic-release/commit-analyzer'
  # - "@semantic-release/release-notes-generator"
  - '@semantic-release/github'
tagFormat: 'v${version}'
