branches:
  - base: main
    channel: stable
    prerelease: false
  - base: develop
    channel: beta
    prerelease: beta
  - base: "feature/*"
    channel: feature
    prerelease: feature
  - base: "hotfix/*"
    channel: hotfix
    prerelease: false
channels:
  - main
  - develop
  - hotfix
  - feature
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
gitTag:
  - true  # Creates git tags automatically
npmPublish: false  # Won't publish to npm
github:
  assets: false  # Skip creating assets (we only need git tags)
